FROM eclipse-temurin:23-jre
WORKDIR /app
LABEL org.opencontainers.image.title="brmusics-api"
LABEL org.opencontainers.image.description="API REST do BRMusics"
COPY brmusics-api-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
