services:
  brmusic-api:
    build: .
    container_name: brmusic-api
    image: ernandopaiva/brmusic-api:1.0.0
    ports:
      - "8082:8081"
    restart: always
    env_file:
      - ./config/
    environment:
      APP_API_INTERNAL_URL: http://brmusic-api:8081
