# Homologação / stage — brmusics-api
services:
  brmusics-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ernandopaiva/brmusics-api:stage
    container_name: brmusics-api
    hostname: brmusics-api
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - ./config/brmusics-api.homolog.env
    environment:
      SPRING_PROFILES_ACTIVE: homolog
      APP_API_INTERNAL_URL: http://brmusics-api:8081
