-- Seed a partir de repertorio_pos_comunhao_acao_gracas.json (idempotente por titulo).
INSERT INTO musica (
    codigo, titulo, autor, interprete_referencia, tom_padrao, categoria_liturgica,
    letra, cifra, link_referencia, observacao, ativo, data_cadastro, data_atualizacao
)
SELECT gen_random_uuid(), v.titulo, v.autor, v.interprete, v.tom, v.categoria,
       v.letra, v.cifra, v.link, v.observacao, TRUE, NOW(), NOW()
FROM (VALUES
    ('SOPRA EM MEU JARDIM', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', 'C', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/sopra-em-meu-jardim/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+SOPRA+EM+MEU+JARDIM', 'Pós-comunhão / ação de graças / oração após a Comunhão'),
    ('ANTÍFONAS DE ADORAÇÃO', 'Nicodemos Costa; Gabriela De Sa; Amanda Pinheiro; Evacy; Cristiano Pinheiro; Leonardo Biondo; Wilde Fabio; Leozany; Rafael Morel; Fabio Lima; Davidson Silva; Sibelle Veiga; Gustavo Osterno; Susi Castro; Dudu Cardoso; Guilherme Pontes; Keciane Lima; Yuri Costa; Justine Lafferriere; Laura Salvador; Mylene Otou; Pedro Veiga; Padre Vicente; Guto Cesar', 'Comunidade Católica Shalom', 'A', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/antifonas-de-adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ANT%C3%8DFONAS+DE+ADORA%C3%87%C3%83O', 'Pós-comunhão / adoração e ação de graças'),
    ('ADORAÇÃO', 'Renato Borges Neto; Gustavo Osterno', 'Comunidade Católica Shalom', 'E', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ADORA%C3%87%C3%83O', 'Pós-comunhão / adoração'),
    ('TODA ADORAÇÃO', 'Gustavo Osterno; Pedro Ivo; Guilherme Pontes; Keciane Lima', 'Comunidade Católica Shalom', 'G', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/toda-adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+TODA+ADORA%C3%87%C3%83O', 'Pós-comunhão / adoração e louvor'),
    ('EM ADORAÇÃO', 'Betho Wilson; Guttemberg Junior', 'Comunidade Católica Shalom', NULL, 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/1270122/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+EM+ADORA%C3%87%C3%83O', 'Pós-comunhão / adoração e gratidão'),
    ('IRRESISTIVELMENTE', 'Nicodemos Costa; Evacy; Gustavo Osterno; Susi Castro; Dudu Cardoso', 'Comunidade Católica Shalom', NULL, 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/irresistivelmente/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+IRRESISTIVELMENTE', 'Pós-comunhão / adoração'),
    ('BANQUETE ETERNO', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', 'A', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/banquete-eterno/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+BANQUETE+ETERNO', 'Pós-comunhão / contemplação eucarística'),
    ('ALMA DE CRISTO', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', 'C', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/alma-de-cristo/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ALMA+DE+CRISTO', 'Pós-comunhão / oração eucarística'),
    ('SANTA MARIA, EU QUERO TE AGRADECER', 'Irmã Míria T. Kolling', 'Músicas Católicas', 'A', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/catolicas/santa-maria-eu-quero-te-agradecer-acao-de-gracas/', 'https://www.youtube.com/results?search_query=M%C3%BAsicas+Cat%C3%B3licas+SANTA+MARIA%2C+EU+QUERO+TE+AGRADECER', 'Ação de graças após a Comunhão / mariana e eucarística'),
    ('EU QUERO ME APAIXONAR', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+EU+QUERO+ME+APAIXONAR', 'Pós-comunhão / oração e adoração'),
    ('SÓ QUERO A TI', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+S%C3%93+QUERO+A+TI', 'Pós-comunhão / adoração'),
    ('LUGAR DE ADORAÇÃO E VIDA', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+LUGAR+DE+ADORA%C3%87%C3%83O+E+VIDA', 'Pós-comunhão / adoração'),
    ('NA TUA PRESENÇA', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+NA+TUA+PRESEN%C3%87A', 'Pós-comunhão / oração e adoração'),
    ('A SÓS CONTIGO', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+A+S%C3%93S+CONTIGO', 'Pós-comunhão / oração pessoal'),
    ('RECEBE ADORAÇÃO', 'Emanuel Stenio', 'Ministério Amor e Adoração', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+RECEBE+ADORA%C3%87%C3%83O', 'Pós-comunhão / adoração'),
    ('FONTE DO VIVER', 'Carlos Eduardo Da Silva; Ana Lucia; Luciana Sitta', 'Ministério Amor e Adoração', 'G', 'POS_COMUNHAO', NULL, 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/fonte-do-viver/', 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+FONTE+DO+VIVER', 'Pós-comunhão / ação de graças e vida em Cristo'),
    ('LINDO CÉU', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+LINDO+C%C3%89U', 'Pós-comunhão / contemplação'),
    ('SÓ EM TI', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+S%C3%93+EM+TI', 'Pós-comunhão / oração'),
    ('DOCE JESUS', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+DOCE+JESUS', 'Pós-comunhão / oração a Jesus'),
    ('TEU AMOR', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+TEU+AMOR', 'Pós-comunhão / ação de graças pelo amor de Deus'),
    ('NADA TEMEREI', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+NADA+TEMEREI', 'Pós-comunhão / confiança'),
    ('MINHA GRAÇA TE BASTA', 'Adriana Arydes', 'Adriana Arydes', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+MINHA+GRA%C3%87A+TE+BASTA', 'Pós-comunhão / oração e confiança'),
    ('COM TUA MÃO', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+COM+TUA+M%C3%83O', 'Pós-comunhão / confiança'),
    ('CONFIO EM TI', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+CONFIO+EM+TI', 'Pós-comunhão / confiança e oração'),
    ('TÃO DENTRO DE MIM', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+T%C3%83O+DENTRO+DE+MIM', 'Pós-comunhão / presença de Cristo'),
    ('SOU SÓ TEU', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+SOU+S%C3%93+TEU', 'Pós-comunhão / entrega'),
    ('SÓ POR TI, JESUS', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+S%C3%93+POR+TI%2C+JESUS', 'Pós-comunhão / entrega e adoração'),
    ('DIANTE DE TI', 'Davidson Silva', 'Davidson Silva', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+DIANTE+DE+TI', 'Pós-comunhão / oração'),
    ('EM TUA PRESENÇA', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+EM+TUA+PRESEN%C3%87A', 'Pós-comunhão / oração e presença de Deus'),
    ('TUDO É DO PAI', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+TUDO+%C3%89+DO+PAI', 'Pós-comunhão / confiança e ação de graças'),
    ('COMO É BOM SENTIR', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+COMO+%C3%89+BOM+SENTIR', 'Pós-comunhão / gratidão pela presença de Deus'),
    ('CHAGAS ABERTAS', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+CHAGAS+ABERTAS', 'Pós-comunhão / oração contemplativa'),
    ('DE TI PRECISO', 'Frei Gilson', 'Frei Gilson', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+DE+TI+PRECISO', 'Pós-comunhão / oração'),
    ('TU ÉS O CENTRO', 'Frei Gilson', 'Frei Gilson', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+TU+%C3%89S+O+CENTRO', 'Pós-comunhão / adoração cristocêntrica'),
    ('EU TE LEVANTAREI', 'Frei Gilson', 'Frei Gilson', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+EU+TE+LEVANTAREI', 'Pós-comunhão / consolo e confiança'),
    ('VEM QUEIMAR O NOSSO CORAÇÃO', 'Frei Gilson', 'Frei Gilson', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+VEM+QUEIMAR+O+NOSSO+CORA%C3%87%C3%83O', 'Pós-comunhão / oração ao Espírito Santo'),
    ('MINHA ESSÊNCIA', 'Thiago Brado', 'Thiago Brado', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Thiago+Brado+MINHA+ESS%C3%8ANCIA', 'Pós-comunhão / entrega e oração'),
    ('NÃO EXISTE AMOR SEM ENTREGA', 'Ir. Míria T. Kolling', 'Ir. Míria T. Kolling', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Ir.+M%C3%ADria+T.+Kolling+N%C3%83O+EXISTE+AMOR+SEM+ENTREGA', 'Pós-comunhão / entrega e amor eucarístico'),
    ('NÓS TE DAMOS MUITAS GRAÇAS', 'Antônio Prado; Frei Joel Postma, OFM', 'CNBB / Música Litúrgica', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=CNBB+%2F+M%C3%BAsica+Lit%C3%BArgica+N%C3%93S+TE+DAMOS+MUITAS+GRA%C3%87AS', 'Pós-comunhão / ação de graças'),
    ('A FORÇA DA EUCARISTIA', 'Ir. Míria T. Kolling', 'Ir. Míria T. Kolling', NULL, 'POS_COMUNHAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Ir.+M%C3%ADria+T.+Kolling+A+FOR%C3%87A+DA+EUCARISTIA', 'Pós-comunhão / ação de graças eucarística')
) AS v(titulo, autor, interprete, tom, categoria, letra, cifra, link, observacao)
WHERE NOT EXISTS (
    SELECT 1 FROM musica m WHERE LOWER(TRIM(m.titulo)) = LOWER(TRIM(v.titulo))
);
