-- Seed a partir de repertorio_adoracao.json (idempotente por titulo).
INSERT INTO musica (
    codigo, titulo, autor, interprete_referencia, tom_padrao, categoria_liturgica,
    letra, cifra, link_referencia, observacao, ativo, data_cadastro, data_atualizacao
)
SELECT gen_random_uuid(), v.titulo, v.autor, v.interprete, v.tom, v.categoria,
       v.letra, v.cifra, v.link, v.observacao, TRUE, NOW(), NOW()
FROM (VALUES
    ('ANTÍFONAS DE ADORAÇÃO', 'Nicodemos Costa; Gabriela De Sa; Amanda Pinheiro; Evacy; Cristiano Pinheiro; Leonardo Biondo; Wilde Fabio; Leozany; Rafael Morel; Fabio Lima; Davidson Silva; Sibelle Veiga; Gustavo Osterno; Susi Castro; Dudu Cardoso; Guilherme Pontes; Keciane Lima; Yuri Costa; Justine Lafferriere; Laura Salvador; Mylene Otou; Pedro Veiga; Padre Vicente; Guto Cesar', 'Comunidade Católica Shalom', 'A', 'ADORACAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/antifonas-de-adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ANT%C3%8DFONAS+DE+ADORA%C3%87%C3%83O', 'Adoração / louvor a Cristo'),
    ('IRRESISTIVELMENTE', 'Nicodemos Costa; Evacy; Gustavo Osterno; Susi Castro; Dudu Cardoso', 'Comunidade Católica Shalom', 'Dm', 'ADORACAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/irresistivelmente/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+IRRESISTIVELMENTE', 'Adoração / entrega diante de Jesus'),
    ('ADORAÇÃO', 'Renato Borges Neto; Gustavo Osterno', 'Comunidade Católica Shalom', 'E', 'ADORACAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ADORA%C3%87%C3%83O', 'Adoração / honra e glória a Jesus'),
    ('TODA ADORAÇÃO', 'Gustavo Osterno; Pedro Ivo; Guilherme Pontes; Keciane Lima', 'Comunidade Católica Shalom', 'G', 'ADORACAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/toda-adoracao/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+TODA+ADORA%C3%87%C3%83O', 'Adoração / entrega de toda a vida'),
    ('PARA ADORAR A TI', 'Renato Borges Neto', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, 'https://www.cifraclub.com.br/comunidade-catolica-shalom/para-adorar-a-ti/', 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+PARA+ADORAR+A+TI', 'Adoração / louvor e entrega'),
    ('SÓ ADORAR', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+S%C3%93+ADORAR', 'Adoração / oração contemplativa'),
    ('VENHO TE ADORAR', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+VENHO+TE+ADORAR', 'Adoração / encontro com Cristo'),
    ('FACE ADORÁVEL', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+FACE+ADOR%C3%81VEL', 'Adoração / contemplação de Cristo'),
    ('MEU TUDO', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+MEU+TUDO', 'Adoração / entrega a Cristo'),
    ('PRESENÇA DIVINA', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+PRESEN%C3%87A+DIVINA', 'Adoração / presença de Deus'),
    ('EU TE ADORO', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+EU+TE+ADORO', 'Adoração / louvor'),
    ('ADORAR-TE, SENHOR', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+ADORAR-TE%2C+SENHOR', 'Adoração / louvor'),
    ('DOCE PRESENÇA', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+DOCE+PRESEN%C3%87A', 'Adoração / presença de Deus'),
    ('JESUS SACRAMENTADO, NOSSO SOL EUCARÍSTICO', 'Comunidade Católica Shalom', 'Comunidade Católica Shalom', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Comunidade+Cat%C3%B3lica+Shalom+JESUS+SACRAMENTADO%2C+NOSSO+SOL+EUCAR%C3%8DSTICO', 'Adoração eucarística'),
    ('LUGAR DE ADORAÇÃO E VIDA', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+LUGAR+DE+ADORA%C3%87%C3%83O+E+VIDA', 'Adoração / presença de Deus'),
    ('RECEBE ADORAÇÃO', 'Emanuel Stenio', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+RECEBE+ADORA%C3%87%C3%83O', 'Adoração / entrega'),
    ('SÓ QUERO A TI', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+S%C3%93+QUERO+A+TI', 'Adoração / desejo de Deus'),
    ('A SÓS CONTIGO', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+A+S%C3%93S+CONTIGO', 'Adoração / oração pessoal'),
    ('NA TUA PRESENÇA', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+NA+TUA+PRESEN%C3%87A', 'Adoração / presença de Deus'),
    ('VOU SUBIR MAIS ALTO', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+VOU+SUBIR+MAIS+ALTO', 'Adoração / busca de Deus'),
    ('VINDES TODOS ADOREMOS', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+VINDES+TODOS+ADOREMOS', 'Adoração / convite à adoração'),
    ('INCOMPARÁVEL SENHOR', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+INCOMPAR%C3%81VEL+SENHOR', 'Adoração / louvor'),
    ('TU ÉS REI', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+TU+%C3%89S+REI', 'Adoração / realeza de Cristo'),
    ('EM ORAÇÃO', 'Ministério Amor e Adoração', 'Ministério Amor e Adoração', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Minist%C3%A9rio+Amor+e+Adora%C3%A7%C3%A3o+EM+ORA%C3%87%C3%83O', 'Adoração / oração'),
    ('DIANTE DE TI', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+DIANTE+DE+TI', 'Adoração / oração diante de Deus'),
    ('DIGNO', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+DIGNO', 'Adoração / Cristo digno de louvor'),
    ('SOU SÓ TEU', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+SOU+S%C3%93+TEU', 'Adoração / entrega'),
    ('SÓ POR TI, JESUS', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+S%C3%93+POR+TI%2C+JESUS', 'Adoração / entrega a Jesus'),
    ('SEJA MEU TUDO', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+SEJA+MEU+TUDO', 'Adoração / entrega total'),
    ('TÚ ÉS O TUDO', 'Davidson Silva', 'Davidson Silva', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Davidson+Silva+T%C3%9A+%C3%89S+O+TUDO', 'Adoração / centralidade de Deus'),
    ('TU ÉS O CENTRO', 'Frei Gilson', 'Frei Gilson', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+TU+%C3%89S+O+CENTRO', 'Adoração / Cristo no centro'),
    ('DE TI PRECISO', 'Frei Gilson', 'Frei Gilson', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Frei+Gilson+DE+TI+PRECISO', 'Adoração / dependência de Deus'),
    ('EM TUA PRESENÇA', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+EM+TUA+PRESEN%C3%87A', 'Adoração / presença de Deus'),
    ('DIANTE DO REI', 'Padre Fábio de Melo', 'Padre Fábio de Melo', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Padre+F%C3%A1bio+de+Melo+DIANTE+DO+REI', 'Adoração / diante de Cristo Rei'),
    ('SÓ EM TI', 'Adriana Arydes', 'Adriana Arydes', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+S%C3%93+EM+TI', 'Adoração / confiança e entrega'),
    ('DOCE JESUS', 'Adriana Arydes', 'Adriana Arydes', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+DOCE+JESUS', 'Adoração / oração a Jesus'),
    ('TEU AMOR', 'Adriana Arydes', 'Adriana Arydes', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Adriana+Arydes+TEU+AMOR', 'Adoração / amor de Deus'),
    ('COMO ÉS LINDO', 'Walmir Alencar; Fabio De Melo', 'Vida Reluz', 'D', 'ADORACAO', NULL, 'https://www.cifraclub.com.br/vida-reluz/como-es-lindo/', 'https://www.youtube.com/results?search_query=Vida+Reluz+COMO+%C3%89S+LINDO', 'Adoração eucarística / presença de Jesus'),
    ('MAJESTOSA EUCARISTIA', 'Anjos de Resgate', 'Anjos de Resgate', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Anjos+de+Resgate+MAJESTOSA+EUCARISTIA', 'Adoração eucarística'),
    ('PRESENÇA REAL', 'Marcos da Matta', 'Marcos da Matta', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=Marcos+da+Matta+PRESEN%C3%87A+REAL', 'Adoração eucarística / presença real de Cristo'),
    ('GLÓRIA A JESUS NA HÓSTIA SANTA', 'Repertório católico tradicional', 'CNBB / Música Litúrgica', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=CNBB+%2F+M%C3%BAsica+Lit%C3%BArgica+GL%C3%93RIA+A+JESUS+NA+H%C3%93STIA+SANTA', 'Adoração eucarística'),
    ('JESUS CRISTO ESTÁ REALMENTE', 'Repertório católico tradicional', 'CNBB / Música Litúrgica', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=CNBB+%2F+M%C3%BAsica+Lit%C3%BArgica+JESUS+CRISTO+EST%C3%81+REALMENTE', 'Adoração eucarística'),
    ('DEUS DE AMOR NÓS TE ADORAMOS', 'Repertório católico tradicional', 'CNBB / Música Litúrgica', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=CNBB+%2F+M%C3%BAsica+Lit%C3%BArgica+DEUS+DE+AMOR+N%C3%93S+TE+ADORAMOS', 'Adoração eucarística'),
    ('VIVA CRISTO, NA HÓSTIA SAGRADA', 'Repertório católico tradicional', 'CNBB / Música Litúrgica', NULL, 'ADORACAO', NULL, NULL, 'https://www.youtube.com/results?search_query=CNBB+%2F+M%C3%BAsica+Lit%C3%BArgica+VIVA+CRISTO%2C+NA+H%C3%93STIA+SAGRADA', 'Adoração eucarística')
) AS v(titulo, autor, interprete, tom, categoria, letra, cifra, link, observacao)
WHERE NOT EXISTS (
    SELECT 1 FROM musica m WHERE LOWER(TRIM(m.titulo)) = LOWER(TRIM(v.titulo))
);
