-- Atualiza link da letra a partir de musicas_link_letra_UTF8_BOM_ponto_virgula.csv
-- Match por LOWER(TRIM(titulo)). Somente linhas com link http(s).
BEGIN;
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/180-graus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('180 GRAUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/a-biblia-comunicacao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A BÍBLIA É COMUNICAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/a-chave-do-coracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A CHAVE DO CORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/a-cruz-sagrada/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A CRUZ SAGRADA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/a-cruz-sagrada-seja-a-minha-luz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A CRUZ SAGRADA SEJA A MINHA LUZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/a-ele-a-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A ELE A GLÓRIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/a-mesa-santa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A MESA SANTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/a-missa-terminou/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A MISSA TERMINOU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/a-oferta-de-maria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A OFERTA DE MARIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/a-paz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A PAZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/a-porta-do-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A PORTA DO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/a-procura/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A PROCURA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/a-santidade-eu-vou-buscar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A SANTIDADE EU VOU BUSCAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/a-sos-contigo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A SÓS CONTIGO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/a-tua-ternura/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A TUA TERNURA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/a-vossa-graca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A VOSSA GRAÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/a-vos-senhor-apresentamos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('A VÓS, SENHOR, APRESENTAMOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/abraco-de-pai/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ABRAÇO DE PAI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/abraco-eterno/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ABRAÇO ETERNO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/abro-as-portas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ABRO AS PORTAS'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3107418/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ACALMA MINHA TEMPESTADE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/aclamacao-ao-evangelho-advento/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ACLAMAÇÃO AO EVANGELHO - ADVENTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/adoracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ADORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/agnus-dei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AGNUS DEI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/aleluia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALELUIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/aleluia-aclamacao-ao-evangelho/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALELUIA - ACLAMAÇÃO AO EVANGELHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/aleluia-aclamemos-a-palavra-do-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALELUIA, ACLAMEMOS A PALAVRA DO SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/aleluia-aleluia-vamos-aclamar-o-evangelho-a-aleluia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALELUIA, ALELUIA! VAMOS ACLAMAR O EVANGELHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/alguem-do-povo-exclama-aclamacao-do-evangelho/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALGUÉM DO POVO EXCLAMA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/alma-de-cristo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ALMA DE CRISTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/amados-por-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AMADOS POR DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/amados-por-deus-gloria-shalom/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AMADOS POR DEUS / GLÓRIA SHALOM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/amar-te-mais/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AMAR-TE MAIS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/amor-nao-amado/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AMOR NÃO AMADO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/amem/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AMÉM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/antifonas-de-adoracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ANTÍFONAS DE ADORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/ao-ouvir-tua-voz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AO OUVIR TUA VOZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/aos-musicos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AOS MÚSICOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/apaixonado/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('APAIXONADO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/apressadamente/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('APRESSADAMENTE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/as-muralhas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('AS MURALHAS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missal-romano/ato-penitencial-2-formula-do-advento/versao-2.html', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL - 3ª FÓRMULA DO ADVENTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/ato-penitencial-senhor-bom-pastor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL - SENHOR BOM PASTOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missa/ato-penitencial/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL - SENHOR QUE SOIS O CAMINHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/melodia-ato-penitencial-pascoa-formula-3-senhor-que-pelo-espirito-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL - TEMPO PASCAL - SENHOR QUE PELO ESPÍRITO SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/marcus-vinicius-lima/ato-penitencial-tempo-pascal-3-opcao-senhor-que-subindo-ao-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL - TEMPO PASCAL - SENHOR QUE SUBINDO AO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/ato-penitencial-do-advento/sjwhthm.html', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL DO ADVENTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/ato-penitencial-kyrie-eleison/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATO PENITENCIAL | KYRIE ELEISON'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/ate-os-confins-da-terra/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ATÉ OS CONFINS DA TERRA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/banquete-eterno/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BANQUETE ETERNO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/basta-uma-so-palavra/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BASTA UMA SÓ PALAVRA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/belo-amor-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BELO AMOR DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/belissimo-esposo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BELÍSSIMO ESPOSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/bendirei-ao-senhor-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BENDIREI AO SENHOR DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/bendito-sejais-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BENDITO SEJAIS SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-fabretti/bendito-sejas-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('BENDITO SEJAS, SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/cada-dia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CADA DIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/cante-em-paz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CANTE EM PAZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/grupo-musical-dom-valioso/canto-final-missa-sertaneja/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CANTO FINAL - MISSA SERTANEJA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/canto-novo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CANTO NOVO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/cancao-nova/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CANÇÃO NOVA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/celebramos-o-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CELEBRAMOS O AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/chagas-abertas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CHAGAS ABERTAS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/cheios-da-tua-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CHEIOS DA TUA GLÓRIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/cheios-de-fervor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CHEIOS DE FERVOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/chuva-de-bencaos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CHUVA DE BENÇÃOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/chuva-de-bencaos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CHUVA DE BÊNÇÃOS'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3149676/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COLO DE MÃE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/com-tua-mao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COM TUA MÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/como-tu-nao-ha/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COMO TU NÃO HÁ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/como-tu-maria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COMO TU, MARIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/como-e-bom-sentir/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COMO É BOM SENTIR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/vida-reluz/como-es-lindo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COMO ÉS LINDO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/compromisso/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COMPROMISSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/confesso-a-deus-ato-penitencial/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CONFESSO A DEUS - ATO PENITENCIAL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/confio-em-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CONFIO EM TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/coracao-de-mae/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORAÇÃO DE MÃE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/coracoes-abrasados/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORAÇÕES ABRASADOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/cordeiro/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/cordeiro-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/cordeiro-de-deus/cordeiro-repete.html', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS - REPETE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/cordeiro-de-deus-7/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS - VERSÃO EM C'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/cordeiro-de-deus-9/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS - VERSÃO EM C (THIAGO GARCIA)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas-2/cordeiro-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS - VERSÃO EM G'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/cordeiro-de-deus-classico/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS CLÁSSICO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/cordeiro-de-deus-i/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CORDEIRO DE DEUS I'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/coroacao-de-nossa-senhora/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('COROAÇÃO DE NOSSA SENHORA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/cristo-ressuscitou-aleluia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CRISTO RESSUSCITOU, ALELUIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/cuida-de-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CUIDA DE MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/cuidas-de-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CUIDAS DE MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/cirio-outra-vez/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('CÍRIO OUTRA VEZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/dai-nos-a-paz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DAI-NOS A PAZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/de-maos-estendida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DE MÃOS ESTENDIDAS'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3448547/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DE TI PRECISO'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3702207/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DEIXA DEUS SONHAR EM TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/derrama-sobre-nos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DERRAMA SOBRE NÓS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/desperta/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DESPERTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/deus-esta-no-controle/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DEUS ESTÁ NO CONTROLE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/deus-existe/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DEUS EXISTE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/deus-habita/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DEUS HABITA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/deus-e-fiel/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DEUS É FIEL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/dia-de-celebrar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIA DE CELEBRAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/dia-de-festa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIA DE FESTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/diante-de-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIANTE DE TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/diante-do-rei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIANTE DO REI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/diante-do-teu-altar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIANTE DO TEU ALTAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/digno/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIGNO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/divino-coracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIVINO CORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/divino-esposo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIVINO ESPOSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/diario-de-maria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DIÁRIO DE MARIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/doce-jesus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DOCE JESUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/doce-mae/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DOCE MÃE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/dois-abismos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DOIS ABISMOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/dons/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('DONS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/eis-me-aqui/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EIS ME AQUI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/ele-cumprira/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ELE CUMPRIRÁ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/ele-venceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ELE VENCEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/1270122/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EM ADORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/em-oracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EM ORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/em-teu-abraco/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EM TEU ABRAÇO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/em-tua-presenca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EM TUA PRESENÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/entre-nos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ENTRE NÓS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/envia-senhor-operarios-para-messe/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ENVIA, SENHOR, OPERÁRIOS PARA A MESSE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/enviai-o-vosso-espirito/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ENVIAI O VOSSO ESPÍRITO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/escolhida-de-deus-pai/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESCOLHIDA DE DEUS PAI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/esposo-ressuscitado/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESPOSO RESSUSCITADO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/espirito-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESPÍRITO SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/estar-em-tuas-maos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESTAR EM TUAS MÃOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/este-e-o-dia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESTE É O DIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/estrangeiro-aqui/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ESTRANGEIRO AQUI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/eterna-vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ETERNA VIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/eterno-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ETERNO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/ato-penitencial-eu-confesso-a-deus-e-vos-irmaos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU CONFESSO A DEUS E A VÓS IRMÃOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/eu-navegarei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU NAVEGAREI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/eu-quero-me-apaixonar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU QUERO ME APAIXONAR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/2757945/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU SEGUIREI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/eu-serei-o-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU SEREI O AMOR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3002060/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU TE LEVANTAREI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/eu-vou-crer-em-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EU VOU CRER EM TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/exemplo-de-esperanca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EXEMPLO DE ESPERANÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/existe-um-louvor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('EXISTE UM LOUVOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/face-adoravel/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FACE ADORÁVEL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/festa-do-cordeiro/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FESTA DO CORDEIRO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/fogo-do-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FOGO DO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/fonte-de-todo-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FONTE DE TODO AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/fonte-de-viver/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FONTE DE VIVER'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/fonte-do-carisma/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FONTE DO CARISMA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/fonte-do-viver/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('FONTE DO VIVER'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/glorioso-rei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLORIOSO REI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA'));
UPDATE musica SET letra = 'https://musicasparamissa.com.br/musica/gloria-pe-silvio-milanez/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA - MISSA PASCAL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/gloria-texto-oficial-da-missa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA - TEXTO OFICIAL DA MISSA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/obra-de-maria/gloria-a-deus-missa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A DEUS (MISSA)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/gloria-a-deus-nas-alturas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A DEUS NAS ALTURAS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/gloria-a-deus-nas-alturas-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A DEUS NAS ALTURAS (GLÓRIA)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/gloria-a-deus-nas-alturas-na-danca-da-vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A DEUS NAS ALTURAS (NA DANÇA DA VIDA) 20 ANOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/gloria-a-deus-nas-alturas-ressuscitou/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A DEUS NAS ALTURAS (RESSUSCITOU) 30 ANOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/gloria-a-jesus-na-hostia-santa-queremos-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA A JESUS NA HÓSTIA SANTA / QUEREMOS DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/gloria-e-esplendor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA E ESPLENDOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/flavio-fonseca/canto-liturgico-de-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GLÓRIA LITÚRGICO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/grande-e-teu-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GRANDE É TEU AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/grande-es/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GRANDE ÉS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/guardioes/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('GUARDIÕES'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/hallelujah/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HALLELUJAH'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/heranca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HERANÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/hey-paraiso/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HEY PARAÍSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/hoje-livre-sou/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOJE LIVRE SOU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/hoje-quero-ser-so-teu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOJE QUERO SER SÓ TEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/holocausto-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOLOCAUSTO DE AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/homem-novo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOMEM NOVO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/hosana/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOSANA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/hosana-nas-alturas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HOSANA NAS ALTURAS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/humano-amor-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('HUMANO AMOR DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/igreja-reunida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('IGREJA REUNIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/imagem-e-semelhanca-do-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('IMAGEM E SEMELHANÇA DO AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/incendeia-minha-alma/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('INCENDEIA MINHA ALMA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/incomparavel-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('INCOMPARÁVEL SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/inigualavel-comunhao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('INIGUALÁVEL COMUNHÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/irresistivelmente/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('IRRESISTIVELMENTE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/jardim-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('JARDIM DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/jesus-voltara/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('JESUS VOLTARÁ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/jesus-e-o-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('JESUS É O SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/marcelo-oliveira-catolico/kyrie-ato-penitencial-tempo-comum/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('KYRIE - ATO PENITENCIAL TEMPO COMUM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/kyrie-eleison/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('KYRIE ELEISON'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/jmj-rio-2013/kyrie-eleison/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('KYRIE ELEISON (JMJ 2013 - LITÚRGICO)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/geo-maia/kyrie-eleison-ato-penitencial/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('KYRIE ELEISON - ATO PENITENCIAL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/ladainha-da-humildade/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LADAINHA DA HUMILDADE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/lado-a-lado/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LADO A LADO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/lindo-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LINDO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/licao-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LIÇÃO DE AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/louvor-da-tua-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LOUVOR DA TUA GLÓRIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/louvor-e-gloria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LOUVOR E GLÓRIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/lugar-de-adoracao-e-vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LUGAR DE ADORAÇÃO E VIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/luz-para-o-meu-caminho/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('LUZ PARA O MEU CAMINHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/magnificat/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MAGNIFICAT'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/mais-que-vencedor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MAIS QUE VENCEDOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/mais-intimo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MAIS ÍNTIMO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/maria/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MARIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/maria-cheia-de-graca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MARIA, CHEIA DE GRAÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/me-conduziras/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ME CONDUZIRÁS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/me-consagro-a-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ME CONSAGRO A TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/mergulhei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MERGULHEI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/mesmo-sendo-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MESMO SENDO DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/meu-bom-pastor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MEU BOM PASTOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/meu-caminho/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MEU CAMINHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/meu-coracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MEU CORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/meu-coracao-esta-pronto-pra-te-amar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MEU CORAÇÃO ESTÁ PRONTO PRA TE AMAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/meu-pai/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MEU PAI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/milagre/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MILAGRE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/milagre-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MILAGRE DE AMOR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3852636/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MINHA FAMÍLIA É UMA BENÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/minha-familia-e-uma-bencao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MINHA FAMÍLIA É UMA BÊNÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/minha-graca-te-basta/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MINHA GRAÇA TE BASTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/padre-zezinho/minha-vida-tem-sentido/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MINHA VIDA TEM SENTIDO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/misericordia-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MISERICÓRDIA SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/misterio-da-fe/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MISTÉRIO DA FÉ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/morada-santa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MORADA SANTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/muito-perdoais/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MUITO PERDOAIS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/muitos-graos-de-trigo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MUITOS GRÃOS DE TRIGO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/mae-de-misericordia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('MÃE DE MISERICÓRDIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/vida-reluz/na-comunhao-te-entregas-a-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NA COMUNHÃO TE ENTREGAS A MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/na-mesa-sagrada/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NA MESA SAGRADA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/na-tua-presenca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NA TUA PRESENÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/nada-nos-separara/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NADA NOS SEPARARÁ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/nada-temerei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NADA TEMEREI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/nada-vai-nos-separar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NADA VAI NOS SEPARAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/nas-asas-do-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NAS ASAS DO SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/no-altar-no-do-meu-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NO ALTAR NO DO MEU SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/nossa-missao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NOSSA MISSÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/nossa-oferta-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NOSSA OFERTA DE AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/novo-dia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('NOVO DIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/o-banquete-do-cordeiro/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O BANQUETE DO CORDEIRO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/o-canto-dos-sinos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O CANTO DOS SINOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/o-elevador/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O ELEVADOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/o-eterno/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O ETERNO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/o-melhor-tu-tens-pra-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O MELHOR TU TENS PRA MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/o-mundo-vai-ouvir-a-sua-voz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O MUNDO VAI OUVIR A SUA VOZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/o-pai-te-espera/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O PAI TE ESPERA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/o-poco/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O POÇO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/o-pao-da-vida-comunhao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('O PÃO DA VIDA - COMUNHÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/oceanos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OCEANOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/oferta/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OFERTA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/oferta-de-louvor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OFERTA DE LOUVOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/oficio-da-imaculada-conceicao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OFÍCIO DA IMACULADA CONCEIÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/oh-senhor-tende-piedade/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OH SENHOR TENDE PIEDADE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/oh-espirito-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OH! ESPÍRITO SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/olha-pra-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('OLHA PRA MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/oracao-de-sao-francisco/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ORAÇÃO DE SÃO FRANCISCO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/oracao-eucaristica/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ORAÇÃO EUCARÍSTICA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/oracao-eucaristica-i/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ORAÇÃO EUCARÍSTICA I'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/pai-nosso/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PAI NOSSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/para-adorar-a-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PARA ADORAR A TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/para-sempre-teu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PARA SEMPRE TEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/parapapa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PARAPAPA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/paz-na-terra/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PAZ NA TERRA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/pegadas-de-tua-ausencia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PEGADAS DE TUA AUSÊNCIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/pelos-pecados-ato-penitencial/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PELOS PECADOS - ATO PENITENCIAL'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/perdoa-me/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PERDOA-ME'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/perdoa-me-versao-liturgica/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PERDOA-ME - VERSÃO LITÚRGICA'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/2873627/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PESCADOR DE HOMENS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/plenitude-da-verdade-kyrie/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PLENITUDE DA VERDADE, KYRIE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/porque-choras/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PORQUE CHORAS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/posso-tudo-posso/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('POSSO TUDO POSSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/pra-te-louvar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PRA TE LOUVAR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/ministerio-amor-e-adoracao/1866371/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('PÃO E VINHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/qual-e-a-chave/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUAL É A CHAVE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/que-poderei-retribuir/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUE PODEREI RETRIBUIR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-jose-weber/que-poderei-retribuir-ao-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUE PODEREI RETRIBUIR AO SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/quem-e-essa/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUEM É ESSA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/quem-e-esse-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUEM É ESSE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/queremos-te-ver/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUEREMOS TE VER'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/quero-confessar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUERO CONFESSAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/quero-ouvir-tua-palavra/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUERO OUVIR TUA PALAVRA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/quero-tua-vontade/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('QUERO TUA VONTADE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/rainha-dos-ceus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RAINHA DOS CÉUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/raios-de-misericordia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RAIOS DE MISERICÓRDIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/recebe-adoracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RECEBE ADORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/redencao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('REDENÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/refugio-e-salvacao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('REFÚGIO E SALVAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/rei-dos-ceus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('REI DOS CÉUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/renova-do-mundo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RENOVA DO MUNDO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/resta-ter-fe/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RESTA TER FÉ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/reunidos-aqui/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('REUNIDOS AQUI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/rios-de-agua-viva/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('RIOS DE ÁGUA VIVA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/nelsinho-correa/sacramento-da-comunhao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SACRAMENTO DA COMUNHÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/sacrificio-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SACRIFÍCIO DE AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/salmo-127/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SALMO 127'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/salvador/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SALVADOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/salve-rainha/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SALVE RAINHA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/salve-rainha-do-ceu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SALVE RAINHA DO CÉU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/salvos-pela-cruz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SALVOS PELA CRUZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/sanctus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANCTUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/santa-maria-eu-quero-te-agradecer-acao-de-gracas/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTA MARIA, EU QUERO TE AGRADECER'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/santo-santo-santo-santo-e-o-senhor-nosso-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO (SANTO, SANTO, SANTO É O SENHOR, NOSSO DEUS)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/santo-2/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO 2'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/santo-espirito-santo-espirito/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO ESPÍRITO, SANTO ESPÍRITO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/santo-ii/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO II'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/santo-iii/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO III'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/santo-iv/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO IV'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cnbb/santo-v/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO V'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/santo-e-o-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO É O SENHOR (CD NA DANÇA DA VIDA)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/santo-e-o-senhor-cd-ressuscitou/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO É O SENHOR (CD RESSUSCITOU)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/santo-santo-santo-senhor-deus-do-universo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO, SANTO, SANTO SENHOR DEUS DO UNIVERSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/santo-santo-santo-e-o-senhor-hosana/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO, SANTO, SANTO É O SENHOR (HOSANA)'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/santo-santo-santo-e-o-senhor-senhor-deus-do-universo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO, SANTO, SANTO É O SENHOR - SENHOR DEUS DO UNIVERSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/santo-santo-santo-senhor-deus-do-universo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO, SANTO, SANTO, SENHOR DEUS DO UNIVERSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/santo-senhor-deus-do-universo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SANTO, SENHOR, DEUS DO UNIVERSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/se-compreendesses-o-dom-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SE COMPREENDESSES O DOM DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/se-nao-for-o-teu-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SE NÃO FOR O TEU AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/se-queres/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SE QUERES'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/segura-a-minha-mao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SEGURA A MINHA MÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/padre-marcelo-rossi/segura-na-mao-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SEGURA NA MÃO DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/seja-meu-tudo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SEJA MEU TUDO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/david-melo/ato-penitencial-senhor-que-viestes-nao-para-condenar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SENHOR QUE VIESTES NÃO PARA CONDENAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/senhor-que-viestes-salvar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SENHOR QUE VIESTES SALVAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/ato-penitencial-senhor-que-vindes-visitar-vosso-povo-na-paz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SENHOR QUE VINDES VISITAR VOSSO POVO NA PAZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/ser-shalom-e-ser-feliz/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SER SHALOM É SER FELIZ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/serei-teu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SEREI TEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/sinal-do-meu-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SINAL DO MEU AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/catolicas/sobe-jerusalem/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SOBE A JERUSALÉM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/sois-o-caminho/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SOIS O CAMINHO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/sopra-em-meu-jardim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SOPRA EM MEU JARDIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/sou-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SOU DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/sou-so-teu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SOU SÓ TEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/suficiente-para-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SUFICIENTE PARA MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/so-adorar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓ ADORAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/so-em-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓ EM TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/so-por-ti-jesus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓ POR TI, JESUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/so-quero-a-ti/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓ QUERO A TI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/so-tu-es-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓ TU ÉS SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/solo-tu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('SÓLO TU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/te-encontrarei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TE ENCONTRAREI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/tende-piedade/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TENDE PIEDADE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/tesouro-e-heranca/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TESOURO E HERANÇA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/frei-gilson/teu-abraco/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TEU ABRAÇO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/teu-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TEU AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/teu-amor-me-sustentara/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TEU AMOR ME SUSTENTARÁ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/toda-adoracao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TODA ADORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/todo-dia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TODO DIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/todo-teu/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TODO TEU'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/todos-os-motivos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TODOS OS MOTIVOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/tome/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TOMÉ'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/tu-es-a-vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TU ÉS A VIDA'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3259766/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TU ÉS O CENTRO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/tu-es-rei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TU ÉS REI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/tua-palavra/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TUA PALAVRA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/tudo-posso/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TUDO POSSO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/tudo-e-do-pai/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TUDO É DO PAI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/tao-dentro-de-mim/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TÃO DENTRO DE MIM'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/tu-es-o-tudo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('TÚ ÉS O TUDO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/padre-zezinho/um-coracao-para-amar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('UM CORAÇÃO PARA AMAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/um-so-corpo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('UM SÓ CORPO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/uma-revolucao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('UMA REVOLUÇÃO'));
UPDATE musica SET letra = 'https://www.letras.mus.br/ministerio-amor-e-adoracao/1882954/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VAMOS CELEBRAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/vem-espirito-de-deus/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM ESPÍRITO DE DEUS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/vem-espirito-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM ESPÍRITO SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/vem-nos-visitar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM NOS VISITAR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/frei-gilson/3143219/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM QUEIMAR O NOSSO CORAÇÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/vem-senhor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM SENHOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/vem-espirito-santo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VEM, ESPÍRITO SANTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/venho-te-adorar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VENHO TE ADORAR'));
UPDATE musica SET letra = 'https://www.letras.mus.br/ministerio-amor-e-adoracao/1943039/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VERBUM PANIS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/adriana/vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/vinde-todos-adoremos/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VINDE TODOS ADOREMOS'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/viver-de-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VIVER DE AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/viver-e-morrer/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VIVER E MORRER'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/viver-pra-mim-e-cristo/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VIVER PRA MIM É CRISTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/vivo-de-misericordia/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VIVO DE MISERICÓRDIA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/voltei/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VOLTEI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/pe-fabio-de-melo/vou-cantar-teu-amor/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VOU CANTAR TEU AMOR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/vou-subir-mais-alto/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VOU SUBIR MAIS ALTO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/vou-voar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VOU VOAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/davidson-silva/vou-voltar/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('VOU VOLTAR'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/comunidade-catolica-shalom/a-casa-do-pai/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('À CASA DO PAI'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/cancao-nova/e-tempo-de-conversao/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('É TEMPO DE CONVERSÃO'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/es-a-escolhida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ÉS A ESCOLHIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/es-a-minha-mae/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ÉS A MINHA MÃE'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/missionario-shalom/es-a-nossa-vida/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('ÉS A NOSSA VIDA'));
UPDATE musica SET letra = 'https://www.cifraclub.com.br/ministerio-amor-e-adoracao/o-senhor-tende-piedade/', data_atualizacao = NOW() WHERE LOWER(TRIM(titulo)) = LOWER(TRIM('Ó SENHOR, TENDE PIEDADE'));
COMMIT;
